apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default "envoy-gateway-config" .Values.configMap.name | quote }}
  namespace: {{ default .Release.Namespace .Values.namespace | quote }}
  labels:
    {{- include "gateway-helm.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  envoy-gateway.yaml: |
    {{- toYaml .Values.envoyGateway | nindent 4 }}
