name: Terraform linting

on:
  push:
    branches:
      - "*"

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout source code

      - uses: actions/cache@v4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v4.1.0
        name: Setup TFLint
        with:
          tflint_version: v0.52.0
      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint with reviewdog
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Post comments as a PR review

  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Cache tfsec binary
        uses: actions/cache@v4
        with:
          path: ~/.tfsec
          key: tfsec-${{ runner.os }}-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            tfsec-${{ runner.os }}-

      - name: Install tfsec (if not cached)
        run: |
          if [ ! -f ~/.tfsec/tfsec ]; then
            mkdir -p ~/.tfsec
            curl -L "https://github.com/aquasecurity/tfsec/releases/download/v1.28.0/tfsec-linux-amd64" -o ~/.tfsec/tfsec
            chmod +x ~/.tfsec/tfsec
          fi
        shell: bash

      - name: Run tfsec
        run: ~/.tfsec/tfsec
