name: AI Gateway Setup

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Multipass
        run: sudo snap install multipass

      - name: Launch Multipass VM
        run: multipass launch lts --name ai-ml-ops --cpus 4 --memory 8G --disk 20G

      - name: Install k3s
        run: |
          multipass exec ai-ml-ops -- sh -c "curl -sfL https://get.k3s.io | sh -"
          sleep 60  # Wait for k3s to fully start

      - name: Set KUBE config
        run: |
          multipass exec ai-ml-ops -- bash -c "mkdir -p ~/.kube && sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config && sudo chown ubuntu:ubuntu ~/.kube/config && chmod 600 ~/.kube/config"
          multipass exec ai-ml-ops -- bash -c 'echo "export KUBECONFIG=~/.kube/config" >> ~/.bashrc'

      - name: Install Terraform
        run: |
          multipass exec ai-ml-ops -- wget https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
          multipass exec ai-ml-ops -- unzip terraform_1.0.0_linux_amd64.zip
          multipass exec ai-ml-ops -- sudo mv terraform /usr/local/bin/

      - name: Install Helm
        run: |
          multipass exec ai-ml-ops -- curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          multipass exec ai-ml-ops -- chmod 700 get_helm.sh
          multipass exec ai-ml-ops -- ./get_helm.sh

      - name: Install KServe
        run: multipass exec ai-ml-ops -- bash -c 'source ~/.bashrc ; curl -s "https://raw.githubusercontent.com/kserve/kserve/release-0.15/hack/quick_install.sh" | bash'

      - name: Mount repository to VM
        run: multipass mount ${{ github.workspace }} ai-ml-ops:/home/ubuntu/repo

      - name: Run Terraform init and apply
        run: multipass exec ai-ml-ops -- bash -c 'source ~/.bashrc ; cd /home/ubuntu/repo/ ; terraform init ; terraform apply -auto-approve'

      - name: Check pods in redis-system namespace
        run: |
          multipass exec ai-ml-ops -- bash -c 'source ~/.bashrc ; kubectl get all -n redis-system'
          multipass exec ai-ml-ops -- bash -c 'source ~/.bashrc ; kubectl wait --for=condition=Ready pod -l app=redis -n redis-system --timeout=5m'
